[package]
name = "zpl-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
zpl-parser = { path = "../zpl-parser" }
zpl-interpreter = { path = "../zpl-interpreter" }
tiny-skia = { workspace = true }
fontdue = { workspace = true }
image = { workspace = true }
